version: '3'
services:
  backend-server:
    build:
      context: .
      dockerfile: docker/vosk-server/Dockerfile
    ports:
      - "5050:5050"

  frontend-server:
    build:
      context: .
      dockerfile: docker/web-app/Dockerfile
    ports:
      - "8080:8080"