version: '3'
services:
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5050:5050"

  frontend-server:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"